name: lint
on:
  push:
    branches:
      - main
      - develop
    pull_request:
      branches:
        - main
        - develop
jobs:
  check-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run linter script
        run: cargo clippy --all-targets -- -D clippy::all -D warnings
      - name: Run tests
        run: cargo test --all-features --workspace
      - name: Check formatting
        run: cargo fmt --all -- --check
